AVAILABLE = 'AVAILABLE'
IN_CART = 'IN_CART'
PENDING = 'PENDING'
BOUGHT = 'BOUGHT'

SALE_STATUSES = (
        (AVAILABLE, AVAILABLE),
        (IN_CART, IN_CART),
        (PENDING, PENDING),
        (BOUGHT, BOUGHT),
)


IN_PROGRESS = 'IN_PROGRESS'
DONE = 'DONE'

PROGRESS_STATUS = (
        (IN_PROGRESS, IN_PROGRESS),
        (DONE, DONE),
)

