# Generated by Django 4.0.5 on 2023-10-16 18:38

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_type', models.CharField(blank=True, choices=[('MEDIA', 'MEDIA'), ('SOURCE_FE', 'SOURCE_FE'), ('SOURCE_BE', 'SOURCE_BE')], max_length=20, null=True)),
                ('size', models.PositiveIntegerField(default=0, help_text='(byte)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
