# Generated by Django 4.0.5 on 2023-10-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='storage',
            name='size',
            field=models.PositiveBigIntegerField(default=0, help_text='(byte)'),
        ),
    ]
