# Generated by Django 4.0.5 on 2023-10-16 19:06

from django.db import migrations, models
import uuid


def create_default_system_config(apps, schema_editor):
    SystemConfig = apps.get_model("system", "SystemConfig")
    SystemConfig.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_storage_options_alter_storage_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fe_dir_name', models.CharField(default='EcourseFE', max_length=50)),
                ('be_dir_name', models.CharField(default='EcourseBE', max_length=50)),
            ],
        ),
        migrations.RunPython(create_default_system_config)
    ]
