# Generated by Django 4.0.5 on 2023-11-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='data_file_name',
            field=models.CharField(default='exported_data.json', max_length=100),
        ),
    ]
