# Generated by Django 4.0.5 on 2022-06-19 11:05

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_activated', models.BooleanField(default=False)),
                ('topic', models.CharField(blank=True, choices=[('organic', 'Organic'), ('inorganic', 'Inorganic')], max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
