# Generated by Django 4.0.5 on 2022-07-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.CharField(blank=True, choices=[('Organic', 'Organic'), ('Inorganic', 'Inorganic')], max_length=20, null=True),
        ),
    ]
