# Generated by Django 4.0.5 on 2022-09-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_topic_alter_course_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='progress',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='progress',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
