# Generated by Django 4.0.5 on 2022-09-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_progress_alter_lesson_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='lesson',
            new_name='lessons',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='document',
            new_name='documents',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='video',
            new_name='videos',
        ),
    ]
