# Generated by Django 4.0.5 on 2022-09-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemanagement',
            old_name='status',
            new_name='sale_status',
        ),
    ]
