# Generated by Django 4.0.5 on 2022-09-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_rename_status_coursemanagement_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_number',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
