# Generated by Django 4.0.5 on 2022-09-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_lesson_lesson_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-sold']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['lesson_number']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
    ]
