# Generated by Django 4.0.5 on 2022-09-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_coursedocument_alter_lesson_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_selling',
            field=models.BooleanField(default=True),
        ),
    ]
