# Generated by Django 4.0.5 on 2022-09-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_is_selling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='coursemanagement',
            options={'ordering': ['course__name']},
        ),
    ]
