# Generated by Django 4.0.5 on 2022-09-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_course_options_alter_coursemanagement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemanagement',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
