# Generated by Django 4.0.5 on 2022-09-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_coursemanagement_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
