# Generated by Django 4.0.5 on 2022-09-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_of_rates',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
