# Generated by Django 4.0.5 on 2022-09-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_remove_course_progress_remove_course_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemanagement',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursemanagement',
            name='sale_status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('IN_CART', 'IN_CART'), ('PENDING', 'PENDING'), ('BOUGHT', 'BOUGHT')], default='AVAILABLE', max_length=15),
        ),
    ]
