# Generated by Django 4.0.5 on 2022-10-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_coursemanagement_is_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
