# Generated by Django 4.0.5 on 2022-10-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_lesson_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_done',
        ),
        migrations.AddField(
            model_name='coursemanagement',
            name='done_lessons',
            field=models.ManyToManyField(blank=True, to='courses.lesson'),
        ),
    ]
