# Generated by Django 4.0.5 on 2022-10-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_uploadfile_duration_uploadfile_file_name'),
        ('courses', '0025_remove_lesson_is_done_coursemanagement_done_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemanagement',
            name='done_lessons',
        ),
        migrations.AddField(
            model_name='coursemanagement',
            name='docs_completed',
            field=models.ManyToManyField(blank=True, to='courses.coursedocument'),
        ),
        migrations.AddField(
            model_name='coursemanagement',
            name='videos_completed',
            field=models.ManyToManyField(blank=True, to='upload.uploadfile'),
        ),
    ]
