# Generated by Django 4.0.5 on 2022-10-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_remove_coursemanagement_done_lessons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_lessons',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='total_documents',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='total_videos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
