# Generated by Django 4.0.5 on 2022-10-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_course_total_lessons_lesson_total_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemanagement',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default='IN_PROGRESS', max_length=20),
        ),
    ]
