# Generated by Django 4.0.5 on 2022-10-15 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0005_uploadfile_duration_uploadfile_file_name'),
        ('courses', '0028_alter_coursemanagement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemanagement',
            name='docs_completed',
        ),
        migrations.RemoveField(
            model_name='coursemanagement',
            name='videos_completed',
        ),
        migrations.CreateModel(
            name='LessonManagement',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default='IN_PROGRESS', max_length=20)),
                ('docs_completed', models.ManyToManyField(blank=True, to='courses.coursedocument')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_mgmt', to='courses.lesson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videos_completed', models.ManyToManyField(blank=True, to='upload.uploadfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
