# Generated by Django 4.0.5 on 2022-10-16 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_coursemanagement_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmanagement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_mngt', to='courses.course'),
        ),
    ]
