# Generated by Django 4.0.5 on 2022-10-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_remove_lessonmanagement_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonmanagement',
            name='status',
        ),
        migrations.AddField(
            model_name='lessonmanagement',
            name='progress',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
