# Generated by Django 4.0.5 on 2022-10-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_course_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedocumentmanagement',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursedocumentmanagement',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessonmanagement',
            name='course',
        ),
        migrations.RemoveField(
            model_name='videomanagement',
            name='course',
        ),
        migrations.RemoveField(
            model_name='videomanagement',
            name='lesson',
        ),
    ]
