# Generated by Django 4.0.5 on 2022-10-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_alter_coursedocumentmanagement_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursedocumentmanagement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='videomanagement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coursedocumentmanagement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='videomanagement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
