# Generated by Django 4.0.5 on 2022-10-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_alter_coursedocumentmanagement_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonmanagement',
            name='progress',
        ),
    ]
