# Generated by Django 4.0.5 on 2022-10-22 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_remove_lessonmanagement_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmanagement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
