# Generated by Django 4.0.5 on 2022-10-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_alter_lessonmanagement_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedocumentmanagement',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
    ]
