# Generated by Django 4.0.5 on 2022-10-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_videomanagement_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedocumentmanagement',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videomanagement',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
