# Generated by Django 4.0.5 on 2022-10-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_coursedocumentmanagement_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmanagement',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
