# Generated by Django 4.0.5 on 2022-10-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_lessonmanagement_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
    ]
