# Generated by Django 4.0.5 on 2022-10-25 13:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0005_uploadfile_duration_uploadfile_file_name'),
        ('courses', '0047_remove_course_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursedocumentmanagement',
            unique_together={('document', 'lesson', 'course', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonmanagement',
            unique_together={('lesson', 'course', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='videomanagement',
            unique_together={('video', 'lesson', 'course', 'user')},
        ),
    ]
