# Generated by Django 4.0.5 on 2023-03-16 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_alter_uploadfile_duration_alter_uploadfile_file_size_and_more'),
        ('settings', '0005_alter_homepagedetail_courses_and_more'),
        ('courses', '0050_coursetitle_course_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='CourseTopic',
        ),
        migrations.RenameField(
            model_name='coursedocument',
            old_name='title',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='upload.uploadimage'),
        ),
        migrations.AlterField(
            model_name='coursedocument',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.uploadfile'),
        ),
    ]
