# Generated by Django 4.0.5 on 2023-03-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_rename_topic_coursetopic_and_more'),
        ('settings', '0006_rename_document_title_headerdetail_document_topic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseTitle',
        ),
    ]
