# Generated by Django 4.0.5 on 2023-03-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_remove_coursedocument_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedocument',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_docs', to='courses.coursetopic'),
        ),
    ]
