# Generated by Django 4.0.5 on 2023-03-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_coursedocument_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopic',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
