# Generated by Django 4.0.5 on 2023-03-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_alter_coursetopic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemanagement',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
