# Generated by Django 4.0.5 on 2023-03-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_alter_coursemanagement_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_of_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursemanagement',
            name='progress',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
