# Generated by Django 4.0.5 on 2023-04-01 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_course_course_of_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='total_lessons',
        ),
    ]
