# Generated by Django 4.0.5 on 2023-04-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_remove_course_total_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemanagement',
            name='user_in_class',
            field=models.BooleanField(null=True),
        ),
    ]
