# Generated by Django 4.0.5 on 2023-04-12 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_coursemanagement_user_in_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedocumentmanagement',
            options={'verbose_name_plural': "Management - Course's Documents"},
        ),
        migrations.AlterModelOptions(
            name='coursemanagement',
            options={'ordering': ['course__name'], 'verbose_name_plural': 'Management - Courses'},
        ),
        migrations.AlterModelOptions(
            name='lessonmanagement',
            options={'verbose_name_plural': 'Management - Lessons'},
        ),
        migrations.AlterModelOptions(
            name='videomanagement',
            options={'verbose_name_plural': 'Management - Videos'},
        ),
    ]
