# Generated by Django 4.0.5 on 2023-05-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0018_rename_user_embedded_url_uploadvideo_use_embedded_url'),
        ('courses', '0060_alter_coursedocumentmanagement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='videos',
            field=models.ManyToManyField(blank=True, to='upload.uploadvideo'),
        ),
        migrations.AlterField(
            model_name='videomanagement',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_mngt', to='upload.uploadvideo'),
        ),
    ]
