# Generated by Django 4.0.5 on 2023-06-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0062_coursemanagement_init_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemanagement',
            name='date_done_quiz',
            field=models.DateTimeField(null=True),
        ),
    ]
