# Generated by Django 4.0.5 on 2023-06-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_coursemanagement_date_done_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemanagement',
            name='date_done_quiz',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
