# Generated by Django 4.0.5 on 2023-09-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0064_alter_coursemanagement_date_done_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_number',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='order'),
        ),
    ]
