# Generated by Django 4.0.5 on 2023-09-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0065_alter_lesson_lesson_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedocument',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='coursedocument',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
