# Generated by Django 4.0.5 on 2023-10-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0067_alter_coursemanagement_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmanagement',
            name='is_done_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
