# Generated by Django 4.0.5 on 2023-10-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0068_lessonmanagement_is_done_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmanagement',
            name='date_done_quiz',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
