# Generated by Django 4.0.5 on 2023-10-02 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0070_lessonmanagement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonmanagement',
            name='date_done_quiz',
        ),
        migrations.RemoveField(
            model_name='lessonmanagement',
            name='is_done_quiz',
        ),
        migrations.CreateModel(
            name='LessonQuizManagement',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_done_quiz', models.BooleanField(default=False)),
                ('date_done_quiz', models.DateTimeField(blank=True, null=True)),
                ('course_mngt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemanagement')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
