# Generated by Django 4.0.5 on 2023-10-05 18:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0072_lessonquizmanagement_start_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursemanagement',
            unique_together={('user', 'course')},
        ),
    ]
