# Generated by Django 4.0.5 on 2023-10-10 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0074_remove_coursemanagement_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonmanagement',
            name='user',
        ),
    ]
