# Generated by Django 4.0.5 on 2023-10-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0075_remove_lessonmanagement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemanagement',
            name='init_data',
        ),
    ]
