# Generated by Django 4.0.5 on 2023-10-12 13:03

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0076_remove_coursemanagement_init_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquizmanagement',
            name='history',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None),
        ),
    ]
