# Generated by Django 4.0.5 on 2023-10-12 13:04

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0077_lessonquizmanagement_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonquizmanagement',
            name='history',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
