# Generated by Django 4.0.5 on 2023-10-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0078_alter_lessonquizmanagement_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonsRemoved',
            fields=[
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons removed',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.lesson',),
        ),
        migrations.AddField(
            model_name='lesson',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
