# Generated by Django 4.0.5 on 2023-10-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0079_lessonsremoved_lesson_removed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonquizmanagement',
            options={'verbose_name_plural': 'Management - Lesson quiz'},
        ),
    ]
