# Generated by Django 4.0.5 on 2023-10-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0080_alter_lessonquizmanagement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
