# Generated by Django 4.0.5 on 2023-10-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0081_course_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='init_data',
            field=models.BooleanField(default=False),
        ),
    ]
