# Generated by Django 4.0.5 on 2023-10-31 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0082_course_init_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemanagement',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
