# Generated by Django 4.0.5 on 2023-11-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0084_course_history_lessons_lesson_history_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='history_lessons',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='history_documents',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='history_videos',
        ),
        migrations.AddField(
            model_name='coursedocumentmanagement',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videomanagement',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
