# Generated by Django 4.0.5 on 2023-11-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0085_remove_course_history_lessons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='structure',
            field=models.JSONField(default={}),
        ),
    ]
