# Generated by Django 4.0.5 on 2023-11-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0086_course_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='structure',
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_location',
            field=models.JSONField(default={}),
        ),
    ]
