# Generated by Django 4.0.5 on 2023-04-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_personalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
