# Generated by Django 4.0.5 on 2023-05-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_remove_personalinfo_name_personalinfo_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name': 'Payment Info', 'verbose_name_plural': 'Payment Info'},
        ),
    ]
