# Generated by Django 4.0.5 on 2023-05-20 04:02

from django.db import migrations, models
from django.db.models import Q


def backup_config(apps, schema_editor):
    Configuration = apps.get_model("configuration", "Configuration")

    config = Configuration.objects.first()
    if config:
        Configuration.objects.filter(~Q(id=config.id)).delete()
    else:
        Configuration.objects.create(document_time_limit=30000)


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_alter_personalinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='document_unlimited_time',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backup_config),
    ]
