# Generated by Django 4.0.5 on 2023-05-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_configuration_document_unlimited_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='document_unlimited_time',
            new_name='unlimited_document_time',
        ),
        migrations.AddField(
            model_name='configuration',
            name='ip_address_limit',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='configuration',
            name='unlimited_ip_addresses',
            field=models.BooleanField(default=False),
        ),
    ]
