# Generated by Django 4.0.5 on 2023-09-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_rename_document_unlimited_time_configuration_unlimited_document_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='user_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
