# Generated by Django 4.0.5 on 2023-10-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_configuration_user_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='display_correct_answer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='display_mark',
            field=models.BooleanField(default=True),
        ),
    ]
