# Generated by Django 4.0.5 on 2023-10-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_configuration_display_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='tracking_views',
            field=models.BooleanField(default=False),
        ),
    ]
