# Generated by Django 4.0.5 on 2023-10-31 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_configuration_tracking_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='use_celery',
            field=models.BooleanField(default=False),
        ),
    ]
