# Generated by Django 4.0.5 on 2024-01-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0012_rename_user_tracking_configuration_tracking_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='new_post_display',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
