# Generated by Django 4.0.5 on 2022-09-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='user_answers',
        ),
    ]
