# Generated by Django 4.0.5 on 2022-09-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_user_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='A',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='B',
            field=models.CharField(default='b', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='C',
            field=models.CharField(default='c', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='D',
            field=models.CharField(default='d', max_length=255),
            preserve_default=False,
        ),
    ]
