# Generated by Django 4.0.5 on 2022-09-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_a_quiz_b_quiz_c_quiz_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
