# Generated by Django 4.0.5 on 2022-10-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_answer_course_alter_answer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='course',
        ),
        migrations.AddField(
            model_name='answer',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
    ]
