# Generated by Django 4.0.5 on 2023-09-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quiz_question_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerchoices',
            options={'ordering': ['choice']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'quiz', 'verbose_name_plural': 'quiz'},
        ),
    ]
