# Generated by Django 4.0.5 on 2023-09-25 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0025_uploadavatar_uploadimage_is_avatar'),
        ('courses', '0066_alter_coursedocument_options_coursedocument_order'),
        ('quiz', '0008_alter_answerchoices_options_alter_quiz_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesQuizAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_type', models.CharField(choices=[('IMAGE', 'IMAGE'), ('TEXT', 'TEXT')], default='TEXT', max_length=20)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.uploadimage')),
            ],
            options={
                'verbose_name': 'Choices quiz - Answers',
                'verbose_name_plural': 'Answer',
                'ordering': ['choice_name__name'],
            },
        ),
        migrations.CreateModel(
            name='ChoicesQuizChoiceName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Choices quiz - Choice name',
                'verbose_name_plural': 'Choice',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChoicesQuizQuestion',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('choices', models.ManyToManyField(blank=True, to='quiz.choicesquizanswer')),
                ('correct_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choicesquizchoicename')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
            options={
                'verbose_name': 'Choices quiz - Questions',
                'verbose_name_plural': 'Question',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MatchColumnQuestion',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('choices', models.ManyToManyField(blank=True, to='quiz.choicesquizanswer')),
                ('correct_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choicesquizchoicename')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
            options={
                'verbose_name': 'Choices quiz - Questions',
                'verbose_name_plural': 'Question',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='QuizManagement',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('question_type', models.CharField(blank=True, choices=[('CHOICES', 'CHOICES')], max_length=20, null=True)),
                ('choices_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choicesquizquestion')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
            options={
                'verbose_name': 'Management',
                'verbose_name_plural': 'Quiz',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=100)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizmanagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User answers',
                'verbose_name_plural': 'Answer',
                'ordering': ['quiz__course'],
            },
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AnswerChoices',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.AddField(
            model_name='choicesquizanswer',
            name='choice_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choicesquizchoicename'),
        ),
    ]
