# Generated by Django 4.0.5 on 2023-09-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0025_uploadavatar_uploadimage_is_avatar'),
        ('quiz', '0009_choicesquizanswer_choicesquizchoicename_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicesquizanswer',
            options={'ordering': ['choice_name__name'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Choices quiz - Answers'},
        ),
        migrations.AlterModelOptions(
            name='choicesquizchoicename',
            options={'ordering': ['name'], 'verbose_name': 'Choice', 'verbose_name_plural': 'Choices quiz - Choice name'},
        ),
        migrations.AlterModelOptions(
            name='choicesquizquestion',
            options={'ordering': ['created'], 'verbose_name': 'Question', 'verbose_name_plural': 'Choices quiz - Questions'},
        ),
        migrations.AlterModelOptions(
            name='quizmanagement',
            options={'ordering': ['course', 'order'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Management'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['quiz__course'], 'verbose_name': 'User answer', 'verbose_name_plural': 'User answers'},
        ),
        migrations.RenameField(
            model_name='choicesquizquestion',
            old_name='content',
            new_name='content_text',
        ),
        migrations.AddField(
            model_name='choicesquizquestion',
            name='content_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.uploadimage'),
        ),
        migrations.AddField(
            model_name='choicesquizquestion',
            name='content_type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('TEXT', 'TEXT')], default='TEXT', max_length=20),
        ),
    ]
