# Generated by Django 4.0.5 on 2023-09-26 17:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0025_uploadavatar_uploadimage_is_avatar'),
        ('quiz', '0010_alter_choicesquizanswer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchColumnContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('IMAGE', 'IMAGE'), ('TEXT', 'TEXT')], default='TEXT', max_length=20)),
                ('content_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.uploadimage')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Match column - Content',
                'ordering': ['content_type', 'content_text'],
            },
        ),
        migrations.AlterModelOptions(
            name='matchcolumnquestion',
            options={'ordering': ['created'], 'verbose_name': 'Match column - Questions', 'verbose_name_plural': 'Question'},
        ),
        migrations.RemoveField(
            model_name='matchcolumnquestion',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='matchcolumnquestion',
            name='content',
        ),
        migrations.RemoveField(
            model_name='matchcolumnquestion',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='matchcolumnquestion',
            name='course',
        ),
        migrations.AddField(
            model_name='quizmanagement',
            name='match_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.matchcolumnquestion'),
        ),
        migrations.AlterField(
            model_name='choicesquizquestion',
            name='content_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.uploadimage'),
        ),
        migrations.AlterField(
            model_name='choicesquizquestion',
            name='content_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizmanagement',
            name='question_type',
            field=models.CharField(blank=True, choices=[('CHOICES', 'CHOICES'), ('MATCH', 'MATCH')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MatchColumnMatchAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_answer_from_first', to='quiz.matchcolumncontent')),
                ('second_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_answer_from_second', to='quiz.matchcolumncontent')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Match column - Match answer',
            },
        ),
        migrations.AddField(
            model_name='matchcolumnquestion',
            name='first_column',
            field=models.ManyToManyField(related_name='questions_from_first_col', to='quiz.matchcolumncontent'),
        ),
        migrations.AddField(
            model_name='matchcolumnquestion',
            name='second_column',
            field=models.ManyToManyField(related_name='questions_from_second_col', to='quiz.matchcolumncontent'),
        ),
    ]
