# Generated by Django 4.0.5 on 2023-09-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_matchcolumncontent_alter_matchcolumnquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchcolumnquestion',
            options={'ordering': ['created'], 'verbose_name': 'Question', 'verbose_name_plural': 'Match column - Questions'},
        ),
        migrations.AddField(
            model_name='matchcolumnquestion',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
