# Generated by Django 4.0.5 on 2023-09-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_matchcolumnquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='match',
            field=models.ManyToManyField(blank=True, help_text='(Match column answers)', to='quiz.matchcolumncontent'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='choice',
            field=models.ForeignKey(blank=True, help_text='(Choices quiz answer)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choicesquizchoicename'),
        ),
    ]
