# Generated by Django 4.0.5 on 2023-09-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_fillblankquestion_alter_quizmanagement_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillblankquestion',
            name='hidden_words',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
