# Generated by Django 4.0.5 on 2023-09-30 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_choicesquizuseranswer_matchcolumnuseranswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicesquizuseranswer',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizmanagement'),
        ),
        migrations.AlterField(
            model_name='matchcolumnuseranswer',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizmanagement'),
        ),
    ]
