# Generated by Django 4.0.5 on 2023-09-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_alter_choicesquizuseranswer_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicesquizquestion',
            name='course',
        ),
    ]
