# Generated by Django 4.0.5 on 2023-10-01 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0067_alter_coursemanagement_mark'),
        ('quiz', '0019_remove_choicesquizquestion_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmanagement',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson'),
        ),
    ]
