# Generated by Django 4.0.5 on 2023-10-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_fillblankuseranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmanagement',
            name='time_limit',
            field=models.PositiveSmallIntegerField(blank=True, help_text='(minutes)', null=True),
        ),
    ]
