# Generated by Django 4.0.5 on 2023-10-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_quizmanagement_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmanagement',
            name='time_limit',
            field=models.PositiveSmallIntegerField(blank=True, help_text='(seconds)', null=True),
        ),
    ]
