# Generated by Django 4.0.5 on 2023-10-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_alter_quizmanagement_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchcolumnmatchanswer',
            name='match_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.matchcolumnquestion'),
        ),
    ]
