# Generated by Django 4.0.5 on 2023-10-24 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_matchcolumnmatchanswer_match_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchcolumnmatchanswer',
            name='first_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_answer_from_first', to='quiz.matchcolumncontent'),
        ),
        migrations.AlterField(
            model_name='matchcolumnmatchanswer',
            name='match_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.matchcolumnquestion'),
        ),
        migrations.AlterField(
            model_name='matchcolumnmatchanswer',
            name='second_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_answer_from_second', to='quiz.matchcolumncontent'),
        ),
    ]
