# Generated by Django 4.0.5 on 2023-11-03 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_quiz_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicesquizuseranswer',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizmanagement'),
        ),
        migrations.AlterField(
            model_name='fillblankuseranswer',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizmanagement'),
        ),
        migrations.AlterField(
            model_name='matchcolumnuseranswer',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizmanagement'),
        ),
    ]
