# Generated by Django 4.0.5 on 2023-11-03 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0029_alter_uploadvideo_video_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0030_alter_choicesquizuseranswer_quiz_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizManagement',
            new_name='QuestionManagement',
        ),
        migrations.RenameModel(
            old_name='ChoicesQuizUserAnswer',
            new_name='ChoicesQuestionUserAnswer',
        ),
        migrations.RenameModel(
            old_name='ChoicesQuizQuestion',
            new_name='ChoicesQuestion',
        ),
        migrations.RenameModel(
            old_name='ChoicesQuizAnswer',
            new_name='ChoicesAnswer',
        ),
        migrations.RenameModel(
            old_name='ChoicesQuizChoiceName',
            new_name='ChoiceName',
        ),

        migrations.RenameField(
            model_name='choicesquestionuseranswer',
            old_name='quiz',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='fillblankuseranswer',
            old_name='quiz',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='matchcolumnuseranswer',
            old_name='quiz',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_mngt',
            new_name='question_mngt',
        ),

        migrations.AlterModelOptions(
            name='choicename',
            options={'ordering': ['name'], 'verbose_name': 'Choice', 'verbose_name_plural': 'Choices - Choice name'},
        ),
        migrations.AlterModelOptions(
            name='choicesanswer',
            options={'ordering': ['choice_name__name'], 'verbose_name': 'Answer',
                     'verbose_name_plural': 'Choices - Answers'},
        ),
        migrations.AlterModelOptions(
            name='choicesquestion',
            options={'ordering': ['created'], 'verbose_name': 'Question', 'verbose_name_plural': 'Choices - Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionmanagement',
            options={'ordering': ['order'], 'verbose_name': 'Question', 'verbose_name_plural': 'Management'},
        ),
    ]
