# Generated by Django 4.0.5 on 2023-11-03 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_choicesquestionuseranswer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicesquestionuseranswer',
            options={'ordering': ['created'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Choices - User answers'},
        ),
        migrations.AlterField(
            model_name='choicesquestionuseranswer',
            name='choice',
            field=models.ForeignKey(blank=True, help_text='(Choices answer)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choicename'),
        ),
    ]
