# Generated by Django 4.0.5 on 2023-11-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_quiz_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillblankquestion',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
