# Generated by Django 4.0.5 on 2022-08-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_thumbnail'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='documents',
            field=models.ManyToManyField(blank=True, to='documents.document'),
        ),
    ]
