# Generated by Django 4.0.5 on 2022-08-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_rename_file_path_uploadimage_image_path_and_more'),
        ('documents', '0002_alter_document_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='upload.uploadimage'),
        ),
    ]
