# Generated by Django 4.0.5 on 2022-08-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_rename_file_path_uploadimage_image_path_and_more'),
        ('documents', '0003_alter_document_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='upload.uploadfile'),
        ),
    ]
