# Generated by Django 4.0.5 on 2022-08-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='is_activated',
            new_name='is_active',
        ),
    ]
