# Generated by Django 4.0.5 on 2022-08-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_rename_file_path_uploadimage_image_path_and_more'),
        ('documents', '0007_rename_is_activated_document_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='files',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='upload.uploadfile'),
        ),
    ]
