# Generated by Django 4.0.5 on 2022-08-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_document_files_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
    ]
