# Generated by Django 4.0.5 on 2022-08-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_userdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDocument',
        ),
    ]
