# Generated by Django 4.0.5 on 2022-08-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_userdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
