# Generated by Django 4.0.5 on 2022-08-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_userdocument_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
