# Generated by Django 4.0.5 on 2022-08-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_document_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
