# Generated by Django 4.0.5 on 2022-08-11 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0016_alter_userdocument_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
