# Generated by Django 4.0.5 on 2022-08-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_document_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDocument',
        ),
    ]
