# Generated by Django 4.0.5 on 2022-08-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_delete_userdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
