# Generated by Django 4.0.5 on 2022-08-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_document_downloads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='downloads',
            new_name='sold',
        ),
    ]
