# Generated by Django 4.0.5 on 2022-08-12 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_rename_downloads_document_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='users',
        ),
    ]
