# Generated by Django 4.0.5 on 2022-09-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_remove_document_users_documentmanagement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentmanagement',
            old_name='status',
            new_name='sale_status',
        ),
    ]
