# Generated by Django 4.0.5 on 2022-09-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_rename_status_documentmanagement_sale_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-sold']},
        ),
    ]
