# Generated by Django 4.0.5 on 2022-09-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_document_is_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmanagement',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
