# Generated by Django 4.0.5 on 2022-09-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_document_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
