# Generated by Django 4.0.5 on 2022-09-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_document_num_of_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmanagement',
            name='sale_status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('IN_CART', 'IN_CART'), ('IN_FAVORITE', 'IN_FAVORITE'), ('PENDING', 'PENDING'), ('BOUGHT', 'BOUGHT')], default='AVAILABLE', max_length=15),
        ),
    ]
