# Generated by Django 4.0.5 on 2022-09-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_alter_documentmanagement_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmanagement',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentmanagement',
            name='sale_status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('IN_CART', 'IN_CART'), ('PENDING', 'PENDING'), ('BOUGHT', 'BOUGHT')], default='AVAILABLE', max_length=15),
        ),
    ]
