# Generated by Django 4.0.5 on 2022-10-15 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0034_documentmanagement_is_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmanagement',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_mngt', to='documents.document'),
        ),
    ]
