# Generated by Django 4.0.5 on 2023-03-16 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_alter_uploadfile_duration_alter_uploadfile_file_size_and_more'),
        ('settings', '0006_rename_document_title_headerdetail_document_topic_and_more'),
        ('documents', '0038_remove_documenttitle_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentTitle',
            new_name='DocumentTopic',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.AddField(
            model_name='document',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs', to='documents.documenttopic'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='upload.uploadfile'),
        ),
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='upload.uploadimage'),
        ),
    ]
