# Generated by Django 4.0.5 on 2023-03-21 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_rename_documenttitle_documenttopic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttopic',
            options={'ordering': ['name']},
        ),
    ]
