# Generated by Django 4.0.5 on 2023-10-05 18:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0040_alter_documenttopic_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentmanagement',
            unique_together={('user', 'document')},
        ),
    ]
