# Generated by Django 4.0.5 on 2023-10-09 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0041_alter_documentmanagement_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmanagement',
            name='last_update',
        ),
    ]
