A = "A"
B = "B"
C = "C"
D = "D"

ANSWER_CHOICES = [
    (A, A),
    (B, B),
    (C, C),
    (D, D),
]


ANSWER_TYPE_IMAGE = "IMAGE"
ANSWER_TYPE_TEXT = "TEXT"

ANSWER_TYPES = [
    (ANSWER_TYPE_IMAGE, ANSWER_TYPE_IMAGE),
    (ANSWER_TYPE_TEXT, ANSWER_TYPE_TEXT),
]


QUESTION_TYPE_CHOICES = "CHOICES"
QUESTION_TYPE_MATCH = "MATCH"
QUESTION_TYPE_FILL = "FILL"

QUESTION_TYPES = [
    (QUESTION_TYPE_CHOICES, QUESTION_TYPE_CHOICES),
    (QUESTION_TYPE_MATCH, QUESTION_TYPE_MATCH),
    (QUESTION_TYPE_FILL, QUESTION_TYPE_FILL),
]

ADMIN_DISPLAY_SUBSTRING = "..."
RESPONSE_SUBSTRING = "{{}}"