from apps.users.choices import MANAGER, TEACHER

REQUEST_STATUS = "request_status"
DOCS_COMPLETED = "docs_completed"
VIDEOS_COMPLETED = "videos_completed"
QUIZ_DETAIL = "quiz_detail"
LIST_QUIZ = "list_quiz"

CLASS_EXTRA_FIELDS = [
    LIST_QUIZ,
    REQUEST_STATUS,
    QUIZ_DETAIL,
    DOCS_COMPLETED,
    VIDEOS_COMPLETED,
]

COURSE_EXTRA_FIELDS = [
    LIST_QUIZ,
    QUIZ_DETAIL,
    DOCS_COMPLETED,
    VIDEOS_COMPLETED,
]

ALL = "ALL"
DOCUMENT = "DOCUMENT"
COURSE = "COURSE"
CLASS = "CLASS"
POST = "POST"

DATA_TYPE_CHOICES = [
    (DOCUMENT, DOCUMENT),
    (COURSE, COURSE),
    (CLASS, CLASS),
    (POST, POST),
]


ADMIN_DISPLAY = {
    "SUPERUSER": {
        "Class": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": [
                "author", "name", "topic", "description", "lessons", 'lessons_remove',
                "thumbnail", "is_selling", "course_of_class", "init_data", "test",
            ],
            "readonly_fields": [],
            "list_filter": ["name", "topic"],
            "search_fields": ["name", "author__email"],
            "list_display": ["name", "topic", "author", "id"],
        },
        "ClassRequest": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["user", "class_request", "accepted"],
            "readonly_fields": [],
            "list_filter": ["class_request__name"],
            "search_fields": ["user__email", "user__full_name", "class_request__name"],
            "list_display": ["user", "name", "class_request", "date_request", "accepted"],
        },
        "ClassManagement": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": [
                "user", "course", "progress", "mark", "status", "is_done_quiz", "date_done_quiz",
                "sale_status", "user_in_class", "views",
            ],
            "readonly_fields": [],
            "list_filter": ["course", "user_in_class"],
            "search_fields": ["user__email", "course__name", "sale_status"],
            "list_display": ["user", "course", "progress", "mark", "is_done_quiz", "user_in_class", "views"],
        },
        "CourseDocument": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["author", "order", "name", "description", "topic", "file"],
            "readonly_fields": [],
            "list_filter": ["topic"],
            "search_fields": ["name", "topic__name", "author__email"],
            "list_display": ["name", "topic", "author", "id"],
        },
        "CourseTopic": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["name", "author"],
            "readonly_fields": [],
            "list_filter": [],
            "search_fields": ["name", "author__email"],
            "list_display": ["name", "author", "id"],
        },
        "Lesson": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["author", "lesson_number", "name", "content", "videos", "documents", "quiz_location"],
            "readonly_fields": [],
            "list_filter": [],
            "search_fields": ["name", "author__email"],
            "list_display": ["name", "lesson_number", "course_include", "class_include", "author", "id"],
        },
        "Course": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": [
                "author", "name", "topic", "description", "lessons", 'lessons_remove',
                "thumbnail", "is_selling", "course_of_class", "init_data", "test",
            ],
            "readonly_fields": [],
            "list_filter": ["topic"],
            "search_fields": ["name", "author__email"],
            "list_display": ["name", "topic", "is_selling", "init_data", "test", "author", "id"],
        },
        "CourseManagement": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": [
                "user", "course", "progress", "mark", "status", "is_done_quiz", "date_done_quiz",
                "sale_status", "user_in_class", "views",
            ],
            "readonly_fields": [],
            "list_filter": ["course__course_of_class", "course", "sale_status"],
            "search_fields": ["user__email", "course__name", "course__author__email", "sale_status"],
            "list_display": ["user", "course", "progress", "mark", "user_in_class", "views"],
        },
        "LessonManagement": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["course", "lesson"],
            "readonly_fields": [],
            "list_filter": ["course"],
            "search_fields": ["course__name"],
            "list_display": ["course", "lesson"],
        },
        "CourseDocumentManagement": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["user", "course", "lesson", "document", "is_completed", "is_available", "enable"],
            "readonly_fields": [],
            "list_filter": ["course", "is_completed", "is_available", "enable"],
            "search_fields": ["course__name", "course__author__email", "user__email"],
            "list_display": ["user", "course", "lesson", "document", "is_completed", "is_available", "enable"],
        },
        "VideoManagement": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["user", "course", "lesson", "video", "is_completed", "is_available", "enable"],
            "readonly_fields": [],
            "list_filter": ["course", "is_completed", "is_available", "enable"],
            "search_fields": ["course__name", "course__author__email", "user__email"],
            "list_display": ["user", "course", "lesson", "video", "is_completed", "is_available", "enable"],
        },
        "QuizManagement": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["user", "course", "lesson", "quiz", "is_done_quiz", "date_done_quiz", "start_time", "history"],
            "readonly_fields": [],
            "list_filter": ["course", "is_done_quiz"],
            "search_fields": ["course__name", "course__author__email", "user__email"],
            "list_display": ["user", "course", "lesson", "quiz", "is_done_quiz", "date_done_quiz"],
        },
        "UploadVideo": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": [
                "author", "order", "video_name", "video_path", "video_embedded_url", "use_embedded_url",
                "video_size", "video_type", "duration", "ip_address",
            ],
            "readonly_fields": [],
            "list_filter": [],
            "search_fields": ["video_name", "video_type"],
            "list_display": [
                "video_name", "video_path", "video_size", "video_type", "duration", "order", "created", "author"
            ],
        },
        "UploadFile": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": [
                "author", "file_name", "file_path", "file_embedded_url", "use_embedded_url",
                "file_size", "file_type", "ip_address",
            ],
            "readonly_fields": [],
            "list_filter": [],
            "search_fields": ["file_name", "file_type"],
            "list_display": ["file_name", "file_path", "file_size", "file_type", "created", "author"],
        },
        "UploadImage": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["author", "image_name", "image_path", "image_size", "image_type", "ip_address", "is_avatar"],
            "readonly_fields": [],
            "list_filter": [],
            "search_fields": ["image_name", "image_type"],
            "list_display": ["image_name", "image_url", "image_size", "image_type", "created", "author"],
        },
        "UploadAvatar": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["author", "image_name", "image_path", "image_size", "image_type", "ip_address", "is_avatar"],
            "readonly_fields": [],
            "list_filter": [],
            "search_fields": ["image_name", "image_type"],
            "list_display": ["image_name", "image_path", "image_size", "image_type", "created", "author"],
        },
        "UploadFolder": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["author", "name", "folder_path"],
            "readonly_fields": [],
            "list_filter": [],
            "search_fields": ["author__email", "name"],
            "list_display": ["name", "author", "created"],
        },
        "Quiz": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["author", "name", "question_mngt"],
            "readonly_fields": [],
            "list_filter": [],
            "search_fields": ["author__email", "name"],
            "list_display": ["name", "author", "created", "id"],
        },
        "User": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": [
                "email", "full_name", "avatar", "phone", "role", "first_login", "last_login",
                "date_joined", "ip_addresses", "unverified_ip_addresses", "other_data", "is_superuser",
                "is_staff", "is_active", "is_testing_user", "groups", "user_permissions",
            ],
            "readonly_fields": [],
            "list_filter": ["role"],
            "search_fields": ["email", "full_name", "phone"],
            "list_display": ["email", "full_name", "phone", "last_login", "date_joined"],
        },
        "Configuration": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": [
                "document_time_limit", "unlimited_document_time", "ip_address_limit", "unlimited_ip_addresses",
                "display_mark", "display_correct_answer", "tracking_api", "tracking_ip", "tracking_device",
                "tracking_views", "use_celery",
            ],
            "readonly_fields": [],
            "list_filter": [],
            "search_fields": [],
            "list_display": [
                "id", "document_time_limit", "unlimited_document_time", "ip_address_limit", "unlimited_ip_addresses",
                "display_mark", "display_correct_answer"
            ],
        },
    },

    MANAGER: {
        "Class": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": [
                "author", "name", "topic", "description", "lessons", 'lessons_remove',
                "thumbnail", "is_selling", "course_of_class",
            ],
            "readonly_fields": ["is_selling", "author"],
            "list_filter": ["name", "topic"],
            "search_fields": ["name", "author__email"],
            "list_display": ["name", "topic", "author", "id"],
        },
        "ClassRequest": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["user", "class_request", "accepted"],
            "readonly_fields": [],
            "list_filter": ["class_request__name"],
            "search_fields": ["user__email", "user__full_name", "class_request__name"],
            "list_display": ["user", "name", "class_request", "date_request", "accepted"],
        },
        "ClassManagement": {
            "has_add_permission": False,
            "has_change_permission": False,
            "has_delete_permission": True,
            "fields": [
                "user", "course", "progress", "mark", "status",
                "sale_status", "user_in_class",
            ],
            "readonly_fields": ["progress", "status", "sale_status"],
            "list_filter": ["course", "user_in_class"],
            "search_fields": ["user__email", "course__name", "sale_status"],
            "list_display": ["user", "course", "progress", "mark", "user_in_class"],
        },
        "CourseDocument": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["author", "order", "name", "description", "topic", "file"],
            "readonly_fields": ["author"],
            "list_filter": ["topic"],
            "search_fields": ["name", "topic__name", "author__email"],
            "list_display": ["name", "topic", "author", "id"],
        },
        "CourseTopic": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["name", "author"],
            "readonly_fields": ["author"],
            "list_filter": [],
            "search_fields": ["name", "author__email"],
            "list_display": ["name", "author", "id"],
        },
        "Lesson": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["author", "lesson_number", "name", "content", "videos", "documents"],
            "readonly_fields": ["author"],
            "list_filter": [],
            "search_fields": ["name", "author__email"],
            "list_display": ["name", "lesson_number", "course_include", "class_include", "author", "id"],
        },
        "Course": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": [
                "author", "name", "topic", "description", "lessons", 'lessons_remove',
                "thumbnail", "is_selling", "course_of_class",
            ],
            "readonly_fields": ["author"],
            "list_filter": ["topic"],
            "search_fields": ["name", "author__email"],
            "list_display": ["name", "topic", "is_selling", "author", "id"],
        },
        "CourseManagement": {
            "has_add_permission": False,
            "has_change_permission": False,
            "has_delete_permission": True,
            "fields": [
                "user", "course", "progress", "mark", "status",
                "sale_status", "user_in_class",
            ],
            "readonly_fields": ["user", "course"],
            "list_filter": ["course__course_of_class", "course", "sale_status"],
            "search_fields": ["user__email", "course__name", "course__author__email", "sale_status"],
            "list_display": ["user", "course", "progress", "mark", "user_in_class"],
        },
        "LessonManagement": {
            "has_add_permission": False,
            "has_change_permission": False,
            "has_delete_permission": True,
            "fields": ["course", "lesson"],
            "readonly_fields": ["course", "lesson"],
            "list_filter": ["course"],
            "search_fields": ["course__name"],
            "list_display": ["course", "lesson"],
        },
        "CourseDocumentManagement": {
            "has_add_permission": False,
            "has_change_permission": False,
            "has_delete_permission": True,
            "fields": ["user", "course", "lesson", "document", "is_completed", "is_available", "enable"],
            "readonly_fields": ["user", "course", "lesson", "document", "is_available"],
            "list_filter": ["course", "is_completed", "is_available", "enable"],
            "search_fields": ["course__name", "course__author__email", "user__email"],
            "list_display": ["user", "course", "lesson", "document", "is_completed", "is_available", "enable"],
        },
        "VideoManagement": {
            "has_add_permission": False,
            "has_change_permission": False,
            "has_delete_permission": True,
            "fields": ["user", "course", "lesson", "video", "is_completed", "is_available", "enable"],
            "readonly_fields": ["user", "course", "lesson", "document", "is_available"],
            "list_filter": ["course", "is_completed", "is_available", "enable"],
            "search_fields": ["course__name", "course__author__email", "user__email"],
            "list_display": ["user", "course", "lesson", "video", "is_completed", "is_available", "enable"],
        },
        "QuizManagement": {
            "has_add_permission": False,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["user", "course", "lesson", "quiz", "is_done_quiz", "date_done_quiz", "start_time", "history"],
            "readonly_fields": [
                "user", "course", "lesson", "quiz", "is_done_quiz", "date_done_quiz", "start_time", "history"
            ],
            "list_filter": ["course", "is_done_quiz"],
            "search_fields": ["course__name", "course__author__email", "user__email"],
            "list_display": ["user", "course", "lesson", "quiz", "is_done_quiz", "date_done_quiz"],
        },
        "UploadVideo": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": [
                "author", "order", "video_name", "video_path", "video_embedded_url", "use_embedded_url",
                "video_size", "video_type", "duration",
            ],
            "readonly_fields": ["video_size", "video_type", "duration", "author"],
            "list_filter": [],
            "search_fields": ["author__email", "video_name", "video_type"],
            "list_display": [
                "video_name", "video_path", "video_size", "video_type", "duration", "order", "created", "author"
            ],
        },
        "UploadFile": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": [
                "author", "file_name", "file_path", "file_embedded_url", "use_embedded_url",
                "file_size", "file_type",
            ],
            "readonly_fields": ["file_size", "file_type", "author"],
            "list_filter": [],
            "search_fields": ["author__email", "file_name", "file_type"],
            "list_display": ["file_name", "file_path", "file_size", "file_type", "created", "author"],
        },
        "UploadImage": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["author", "image_name", "image_path", "image_size", "image_type", "is_avatar"],
            "readonly_fields": ["author", "image_size", "image_type"],
            "list_filter": [],
            "search_fields": ["author__email", "image_name", "image_type"],
            "list_display": ["image_name", "image_url", "image_size", "image_type", "created", "author"],
        },
        "UploadAvatar": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["author", "image_name", "image_path", "image_size", "image_type", "is_avatar"],
            "readonly_fields": ["author", "image_size", "image_type"],
            "list_filter": [],
            "search_fields": ["author__email", "image_name", "image_type"],
            "list_display": ["image_name", "image_path", "image_size", "image_type", "created", "author"],
        },
        "UploadFolder": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["author", "name", "folder_path"],
            "readonly_fields": ["author"],
            "list_filter": [],
            "search_fields": ["author__email", "name"],
            "list_display": ["name", "author", "created"],
        },
        "Quiz": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["author", "name", "question_mngt"],
            "readonly_fields": ["author"],
            "list_filter": [],
            "search_fields": ["author__email", "name"],
            "list_display": ["name", "author", "created", "id"],
        },
        "User": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": [
                "email", "full_name", "avatar", "phone", "role", "first_login", "last_login",
                "date_joined", "is_staff", "is_active", "groups", "user_permissions",
            ],
            "readonly_fields": ["date_joined", "first_login", "last_login"],
            "list_filter": ["role"],
            "search_fields": ["email", "full_name", "phone"],
            "list_display": ["email", "full_name", "phone", "last_login", "date_joined"],
        },
        "Configuration": {
            "has_add_permission": False,
            "has_change_permission": True,
            "has_delete_permission": False,
            "fields": [
                "document_time_limit", "unlimited_document_time", "ip_address_limit", "unlimited_ip_addresses",
                "display_mark", "display_correct_answer", "use_celery",
            ],
            "readonly_fields": [],
            "list_filter": [],
            "search_fields": [],
            "list_display": [
                "id", "document_time_limit", "unlimited_document_time", "ip_address_limit", "unlimited_ip_addresses",
                "display_mark", "display_correct_answer"
            ],
        },
    },

    TEACHER: {
        "Class": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": [
                "name", "topic", "description", "lessons", 'lessons_remove',
                "thumbnail", "is_selling", "course_of_class",
            ],
            "readonly_fields": ["is_selling"],
            "list_filter": ["name", "topic"],
            "search_fields": ["name"],
            "list_display": ["name", "topic", "id"],
        },
        "ClassRequest": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["user", "class_request", "accepted"],
            "readonly_fields": [],
            "list_filter": ["class_request__name"],
            "search_fields": ["user__email", "user__full_name", "class_request__name"],
            "list_display": ["user", "name", "class_request", "date_request", "accepted"],
        },
        "ClassManagement": {
            "has_add_permission": False,
            "has_change_permission": False,
            "has_delete_permission": True,
            "fields": [
                "user", "course", "progress", "mark", "status",
                "sale_status", "user_in_class",
            ],
            "readonly_fields": ["progress", "status", "sale_status"],
            "list_filter": ["course", "user_in_class"],
            "search_fields": ["user__email", "course__name", "sale_status"],
            "list_display": ["user", "course", "progress", "mark", "user_in_class"],
        },
        "CourseDocument": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["order", "name", "description", "topic", "file"],
            "readonly_fields": [],
            "list_filter": ["topic"],
            "search_fields": ["name", "topic__name"],
            "list_display": ["name", "topic", "id"],
        },
        "CourseTopic": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["name"],
            "readonly_fields": [],
            "list_filter": [],
            "search_fields": ["name"],
            "list_display": ["name", "id"],
        },
        "Lesson": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["lesson_number", "name", "content", "videos", "documents"],
            "readonly_fields": [],
            "list_filter": [],
            "search_fields": ["name"],
            "list_display": ["name", "lesson_number", "course_include", "class_include", "id"],
        },
        "Course": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": [
                "name", "topic", "description", "lessons", 'lessons_remove',
                "thumbnail", "is_selling", "course_of_class",
            ],
            "readonly_fields": [],
            "list_filter": ["topic"],
            "search_fields": ["name"],
            "list_display": ["name", "topic", "is_selling", "id"],
        },
        "CourseManagement": {
            "has_add_permission": False,
            "has_change_permission": False,
            "has_delete_permission": True,
            "fields": [
                "user", "course", "progress", "mark", "status",
                "sale_status", "user_in_class",
            ],
            "readonly_fields": ["user", "course"],
            "list_filter": ["course__course_of_class", "course", "sale_status"],
            "search_fields": ["user__email", "course__name", "sale_status"],
            "list_display": ["user", "course", "progress", "mark", "user_in_class"],
        },
        "LessonManagement": {
            "has_add_permission": False,
            "has_change_permission": False,
            "has_delete_permission": True,
            "fields": ["course", "lesson"],
            "readonly_fields": ["course", "lesson"],
            "list_filter": ["course"],
            "search_fields": ["course__name"],
            "list_display": ["course", "lesson"],
        },
        "CourseDocumentManagement": {
            "has_add_permission": False,
            "has_change_permission": False,
            "has_delete_permission": True,
            "fields": ["user", "course", "lesson", "document", "is_completed", "is_available", "enable"],
            "readonly_fields": ["user", "course", "lesson", "document", "is_available"],
            "list_filter": ["course", "is_completed", "is_available", "enable"],
            "search_fields": ["course__name", "user__email"],
            "list_display": ["user", "course", "lesson", "document", "is_completed", "is_available", "enable"],
        },
        "VideoManagement": {
            "has_add_permission": False,
            "has_change_permission": False,
            "has_delete_permission": True,
            "fields": ["user", "course", "lesson", "video", "is_completed", "is_available", "enable"],
            "readonly_fields": ["user", "course", "lesson", "document", "is_available"],
            "list_filter": ["course", "is_completed", "is_available", "enable"],
            "search_fields": ["course__name", "user__email"],
            "list_display": ["user", "course", "lesson", "video", "is_completed", "is_available", "enable"],
        },
        "QuizManagement": {
            "has_add_permission": False,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["user", "course", "lesson", "quiz", "is_done_quiz", "date_done_quiz", "start_time", "history"],
            "readonly_fields": [
                "user", "course", "lesson", "quiz", "is_done_quiz", "date_done_quiz", "start_time", "history",
            ],
            "list_filter": ["course", "is_done_quiz"],
            "search_fields": ["course__name", "user__email"],
            "list_display": ["user", "course", "lesson", "quiz", "is_done_quiz", "date_done_quiz"],
        },
        "UploadVideo": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": [
                "order", "video_name", "video_path", "video_embedded_url", "use_embedded_url",
                "video_size", "video_type", "duration", "ip_address",
            ],
            "readonly_fields": ["video_size", "video_type", "duration"],
            "list_filter": [],
            "search_fields": ["video_name", "video_type"],
            "list_display": [ "video_name", "video_path", "video_size", "video_type", "duration", "order", "created"],
        },
        "UploadFile": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["file_name", "file_path", "file_embedded_url", "use_embedded_url", "file_size", "file_type"],
            "readonly_fields": ["file_size", "file_type"],
            "list_filter": [],
            "search_fields": ["file_name", "file_type"],
            "list_display": ["file_name", "file_path", "file_size", "file_type", "created"],
        },
        "UploadImage": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["image_name", "image_path", "image_size", "image_type"],
            "readonly_fields": ["image_size", "image_type"],
            "list_filter": [],
            "search_fields": ["image_name", "image_type"],
            "list_display": ["image_name", "image_url", "image_size", "image_type", "created"],
        },
        "UploadAvatar": {
            "has_add_permission": False,
            "has_change_permission": False,
            "has_delete_permission": False,
            "fields": [],
            "readonly_fields": [],
            "list_filter": [],
            "search_fields": [],
            "list_display": [],
        },
        "UploadFolder": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["name", "folder_path"],
            "readonly_fields": [],
            "list_filter": [],
            "search_fields": ["name"],
            "list_display": ["name", "created"],
        },
        "Quiz": {
            "has_add_permission": True,
            "has_change_permission": True,
            "has_delete_permission": True,
            "fields": ["name", "question_mngt"],
            "readonly_fields": [],
            "list_filter": [],
            "search_fields": ["name"],
            "list_display": ["name", "created", "id"],
        },
        "User": {
            "has_add_permission": False,
            "has_change_permission": False,
            "has_delete_permission": False,
            "fields": ["email", "full_name", "avatar", "phone", "last_login"],
            "readonly_fields": ["date_joined", "first_login", "last_login"],
            "list_filter": [],
            "search_fields": ["email", "full_name", "phone"],
            "list_display": ["email", "full_name", "phone", "last_login"],
        },
        "Configuration": {
            "has_add_permission": False,
            "has_change_permission": False,
            "has_delete_permission": False,
            "fields": [
                "document_time_limit", "unlimited_document_time", "ip_address_limit", "unlimited_ip_addresses",
                "display_mark", "display_correct_answer", "use_celery",
            ],
            "readonly_fields": [],
            "list_filter": [],
            "search_fields": [],
            "list_display": [
                "id", "document_time_limit", "unlimited_document_time", "ip_address_limit", "unlimited_ip_addresses",
                "display_mark", "display_correct_answer"
            ],
        },
    },
}
