REQUEST_STATUS = "request_status"
DOCS_COMPLETED = "docs_completed"
VIDEOS_COMPLETED = "videos_completed"
QUIZ_DETAIL = "quiz_detail"
LIST_QUIZ = "list_quiz"

CLASS_EXTRA_FIELDS = [
    REQUEST_STATUS,
    QUIZ_DETAIL,
    DOCS_COMPLETED,
    VIDEOS_COMPLETED,
]

COURSE_EXTRA_FIELDS = [
    LIST_QUIZ,
    QUIZ_DETAIL,
    DOCS_COMPLETED,
    VIDEOS_COMPLETED,
]
