# Generated by Django 4.0.5 on 2022-10-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replycomment',
            options={'ordering': ['-created']},
        ),
    ]
