# Generated by Django 4.0.5 on 2023-09-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_content_alter_replycomment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replycomment',
            options={'ordering': ['created']},
        ),
    ]
