# Generated by Django 4.0.5 on 2023-02-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userresetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresetpassword',
            name='password_reset',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
