# Generated by Django 4.0.5 on 2023-05-28 08:13

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userresetpassword_is_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_addresses',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=None),
        ),
    ]
