# Generated by Django 4.0.5 on 2023-05-28 09:17

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_unverified_ip_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ip_addresses',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=15), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='unverified_ip_addresses',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=15), null=True, size=None),
        ),
    ]
