# Generated by Django 4.0.5 on 2023-09-10 16:36

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_ip_addresses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTracking',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('query_params', models.JSONField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
