# Generated by Django 4.0.5 on 2023-09-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_usertracking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertracking',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
