# Generated by Django 4.0.5 on 2023-09-19 17:16

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_usertracking_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'Test Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_testing_user',
            field=models.BooleanField(default=False),
        ),
    ]
