# Generated by Django 4.0.5 on 2023-09-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_testuser_user_is_testing_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['full_name', 'email']},
        ),
    ]
