# Generated by Django 4.0.5 on 2023-09-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'MANAGER'), ('STUDENT', 'STUDENT')], default='STUDENT', max_length=50),
        ),
    ]
