# Generated by Django 4.0.5 on 2023-10-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_userdatabackup_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_data',
            field=models.JSONField(default=dict),
        ),
    ]
