# Generated by Django 4.0.5 on 2023-10-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_other_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='other_data',
            field=models.JSONField(default=dict(classes=dict(), courses=dict(), docs=dict(), posts=dict())),
        ),
    ]
