# Generated by Django 4.0.5 on 2023-10-28 11:53

from django.db import migrations, models


def update_data(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.all().update(other_data=dict())


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_other_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='other_data',
            field=models.JSONField(default={}),
        ),
        migrations.RunPython(update_data),
    ]
