# Generated by Django 4.0.5 on 2023-10-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_first_login_alter_user_other_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='other_data',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
