# Generated by Django 4.0.5 on 2023-11-02 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_user_other_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertracking',
            options={'verbose_name': 'Object', 'verbose_name_plural': 'API tracking'},
        ),
        migrations.CreateModel(
            name='DeviceTracking',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(blank=True, choices=[('MOBILE', 'MOBILE'), ('TABLET', 'TABLET'), ('PC', 'PC')], max_length=10, null=True)),
                ('device', models.CharField(blank=True, max_length=20, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=20, null=True)),
                ('system', models.CharField(blank=True, max_length=50, null=True)),
                ('system_version', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Object',
                'verbose_name_plural': 'Device tracking',
            },
        ),
    ]
