# Generated by Django 4.0.5 on 2023-11-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_usertracking_options_devicetracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Admin Permission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'MANAGER'), ('TEACHER', 'TEACHER'), ('STUDENT', 'STUDENT')], default='STUDENT', max_length=50),
        ),
    ]
