# Generated by Django 4.0.5 on 2023-11-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_user_is_staff_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quiz_permission',
            field=models.BooleanField(default=False),
        ),
    ]
