# Generated by Django 4.0.5 on 2022-08-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_uploadimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='file_path',
            new_name='image_path',
        ),
        migrations.RenameField(
            model_name='uploadimage',
            old_name='file_size',
            new_name='image_size',
        ),
        migrations.RenameField(
            model_name='uploadimage',
            old_name='file_type',
            new_name='image_type',
        ),
    ]
