# Generated by Django 4.0.5 on 2022-09-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_rename_file_path_uploadimage_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='user',
        ),
    ]
