# Generated by Django 4.0.5 on 2023-03-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_uploadfile_duration_uploadfile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Seconds'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_size',
            field=models.PositiveBigIntegerField(help_text='(KB)', null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image_size',
            field=models.PositiveBigIntegerField(help_text='(KB)', null=True),
        ),
    ]
