# Generated by Django 4.0.5 on 2023-03-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_alter_uploadfile_duration_alter_uploadfile_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
