# Generated by Django 4.0.5 on 2023-03-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_uploadimage_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Seconds', null=True),
        ),
    ]
