# Generated by Django 4.0.5 on 2023-04-07 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_alter_uploadfile_options_alter_uploadimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
