# Generated by Django 4.0.5 on 2023-05-11 14:19

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid
from apps.upload.enums import video_ext_list


def clone_video(apps, schema_editor):
    UploadFile = apps.get_model("upload", "UploadFile")
    UploadVideo = apps.get_model("upload", "UploadVideo")
    videos = []
    for obj in UploadFile.objects.all():
        if isinstance(obj.file_type, str) and obj.file_type.upper() in video_ext_list:
            videos.append(
                (
                    UploadVideo(
                        video_name=obj.file_name,
                        video_path=obj.file_path,
                        video_size=obj.file_size,
                        video_type=obj.file_type,
                        duration=obj.duration,
                    ),
                    obj.id,
                )
            )

    if videos:
        UploadVideo.objects.bulk_create([tpl[0] for tpl in videos])
        UploadFile.objects.filter(id__in=[tpl[1] for tpl in videos]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_uploaddocument_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_name', models.CharField(blank=True, max_length=255, null=True)),
                ('video_path', models.FileField(blank=True, max_length=128, null=True, upload_to='')),
                ('video_size', models.PositiveBigIntegerField(help_text='(KB)', null=True)),
                ('video_type', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Seconds', null=True)),
            ],
            options={
                'ordering': ['video_name'],
            },
        ),
        migrations.RunPython(clone_video),
    ]
