# Generated by Django 4.0.5 on 2023-05-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0015_uploadvideo_remove_uploadfile_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='duration',
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='video_embedded_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
