# Generated by Django 4.0.5 on 2023-05-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0016_remove_uploadfile_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideo',
            name='user_embedded_url',
            field=models.BooleanField(default=False),
        ),
    ]
