# Generated by Django 4.0.5 on 2023-05-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0017_uploadvideo_user_embedded_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadvideo',
            old_name='user_embedded_url',
            new_name='use_embedded_url',
        ),
    ]
