# Generated by Django 4.0.5 on 2023-05-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0020_alter_uploadfile_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file_embedded_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='use_embedded_url',
            field=models.BooleanField(default=False),
        ),
    ]
