# Generated by Django 4.0.5 on 2023-05-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0021_uploadfile_file_embedded_url_and_more'),
        ('upload', '0021_uploadfile_ip_address_uploadimage_ip_address_and_more'),
    ]

    operations = [
    ]
