# Generated by Django 4.0.5 on 2023-09-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0022_merge_20230523_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadvideo',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_embedded_url',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='video_embedded_url',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
    ]
