# Generated by Django 4.0.5 on 2023-09-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0023_alter_uploadvideo_options_uploadvideo_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file_embedded_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='video_embedded_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
