# Generated by Django 4.0.5 on 2023-10-06 09:01

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0025_uploadavatar_uploadimage_is_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFolder',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('folder_path', models.FileField(blank=True, help_text='(.zip file)', max_length=255, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]