# Generated by Django 4.0.5 on 2023-10-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0028_alter_uploadvideo_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideo',
            name='video_path',
            field=models.FileField(blank=True, help_text='(Support: .mp4 .mov .flv .f4v .mkv .webm .ogg)', max_length=255, null=True, upload_to=''),
        ),
    ]
