# Generated by Django 4.0.5 on 2023-01-12 09:09

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_headerdetail_course_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('documents', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.UUIDField(), blank=True, null=True, size=None)),
                ('courses', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.UUIDField(), blank=True, null=True, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='headerdetail',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
