# Generated by Django 4.0.5 on 2023-03-20 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_rename_document_title_headerdetail_document_topic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagedetail',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='homepagedetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 20, 16, 36, 30, 92530)),
            preserve_default=False,
        ),
    ]
