# Generated by Django 4.0.5 on 2023-03-21 14:48

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_headerdetail_options_remove_header_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagedetail',
            name='classes',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='homepagedetail',
            name='posts',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
