# Generated by Django 4.0.5 on 2023-03-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_homepagedetail_classes_homepagedetail_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='data_type',
            field=models.CharField(blank=True, choices=[('DOCUMENT', 'DOCUMENT'), ('COURSE', 'COURSE'), ('CASS', 'CASS'), ('POST', 'POST')], max_length=20, null=True),
        ),
    ]
