# Generated by Django 4.0.5 on 2023-03-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_alter_header_data_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='header',
            name='order',
            field=models.SmallIntegerField(default=1),
        ),
    ]
