# Generated by Django 4.0.5 on 2023-04-03 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_remove_course_total_lessons'),
        ('settings', '0012_alter_header_options_header_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerdetail',
            name='class_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_header_detail', to='courses.coursetopic'),
        ),
    ]
