# Generated by Django 4.0.5 on 2023-05-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_alter_headerdetail_class_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headerdetail',
            old_name='course_topic',
            new_name='course_and_class_topic',
        ),
        migrations.RemoveField(
            model_name='headerdetail',
            name='class_topic',
        ),
    ]
