# Generated by Django 4.0.5 on 2023-12-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
