# Generated by Django 4.0.5 on 2023-03-20 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'class', 'verbose_name_plural': 'classes'},
        ),
    ]
