# Generated by Django 4.0.5 on 2023-03-20 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_alter_class_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
