# Generated by Django 4.0.5 on 2023-04-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_classmanagement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
