# Generated by Django 4.0.5 on 2023-04-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_alter_headerdetail_class_topic'),
        ('classes', '0010_delete_class'),
        ('courses', '0058_remove_course_total_lessons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassTopic',
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.course',),
        ),
    ]
