# Generated by Django 4.0.5 on 2023-04-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_delete_classtopic_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'class', 'verbose_name_plural': 'classes'},
        ),
    ]
