# Generated by Django 4.0.5 on 2023-04-12 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_alter_class_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classmanagement',
            options={'verbose_name_plural': 'Management - Classes'},
        ),
    ]
