# Generated by Django 4.0.5 on 2023-09-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_alter_classmanagement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classrequest',
            options={'ordering': ['user__full_name']},
        ),
    ]
