AVAILABLE = 'AVAILABLE'
IN_CART = 'IN_CART'
PENDING = 'PENDING'
BOUGHT = 'BOUGHT'

STATUSES = (
        (AVAILABLE, AVAILABLE),
        (IN_CART, IN_CART),
        (PENDING, PENDING),
        (BOUGHT, BOUGHT),
)