# Generated by Django 4.0.5 on 2022-10-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_rating_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created']},
        ),
    ]
