# Generated by Django 4.0.5 on 2022-10-30 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_alter_lessonmanagement_unique_together_and_more'),
        ('documents', '0035_alter_documentmanagement_document'),
        ('rating', '0004_alter_courserating_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserating',
            old_name='rating',
            new_name='ratings',
        ),
        migrations.RenameField(
            model_name='documentrating',
            old_name='rating',
            new_name='ratings',
        ),
        migrations.AlterField(
            model_name='courserating',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_obj', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='documentrating',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_obj', to='documents.document'),
        ),
    ]
