# Generated by Django 4.0.5 on 2022-09-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_lesson_course_lessons_and_more'),
        ('payment', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='orders', to='courses.course'),
        ),
    ]
