# Generated by Django 4.0.5 on 2022-09-18 06:05

from django.db import migrations, models


def update_order_code(apps, schema_editor):
    Order = apps.get_model("payment", "Order")

    list_orders = []
    for order in Order.objects.all():
        order.code = order.code.split("-")[0]
        list_orders.append(order)

    Order.objects.bulk_update(list_orders, fields=["code"])


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_courses'),
    ]

    operations = [
        migrations.RunPython(update_order_code)
    ]
