# Generated by Django 4.0.5 on 2023-08-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_update_order_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created']},
        ),
    ]
