# Generated by Django 4.0.5 on 2023-05-14 03:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_content1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content1',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
