# Generated by Django 4.0.5 on 2023-05-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
